export const actions = {
  quiz: {
    DATA_FETCHING: "QUIZ_DATA_FETCHING",
    DATA_FETCHED: "QUIZ_DATA_FETCHED",
    DATA_FETCH_ERROR: "QUIZ_DATA_FETCH_ERROR",
    USER_DATA_EDITED: "QUIZ_DATA_EDITED",
  },
};
